accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskCreateView, TaskUpdateView, TasklistView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TasklistView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        "auth.User", related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from projects.models import Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    context_object_name = "project_detail"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]
    context_object_name = "create"

    def get_success_url(self):
        return reverse_lazy("show_project", kwargs={"pk": self.object.id})

tasks/views.py
from django.urls import reverse_lazy
from tasks.models import Task
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]
    context_object_name = "create"

    def get_success_url(self):
        return reverse_lazy(
            "show_project", kwargs={"pk": self.object.project.id}
        )


class TasklistView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/edit.html"
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Projects</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url "show_my_tasks" %}">My Tasks</a> </li>
                        <li><a href="{% url "list_projects" %}">My projects</a> </li>
                        <li><a href="{% url "logout" %}">Logout</a> </li>
                    {% else %}
                        <li><a href="{% url "login" %}">Login</a> </li>
                        <li><a href="{% url "signup" %}">Signup</a> </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h1>Create a new project</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends "base.html" %}
{% block content %}
    {% load markdownify %}
    <div>
        <h1>{{project_detail}}</h1>
        {{project_detail.description|markdownify}}
        <h2>Tasks</h2>
        <p><a href="{% url "create_task" %}">Create a new task</p></a>
        {%if project_detail.tasks.all|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deets in project_detail.tasks.all %}
                        <tr>
                            <td>{{deets.name}}</td>
                            <td>{{deets.assignee}}</td>
                            <td>{{deets.start_date}}</td>
                            <td>{{deets.due_date}}</td>
                            <td>
                                {%if deets.is_completed == True%}
                                    Done
                                {% else %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
        {% else %}
            <p>This project has no tasks<p>
            </table>
        {% endif %}
    </div>
{% endblock content %}

projects/templates/projects/list.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>My Projects</h1>
        <p><a href="{% url "create_project" %}">Create a new project</p></a>
        {% if project_list|length < 1 %}
            <p>You are not assigned to any projects</p>
        {% else %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {%for projects in project_list%}
                        <tr>
                            <td><a href="{% url "show_project" projects.id %}">{{projects.name}}</a></td>
                            <td>{{projects.tasks.all|length}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock content %}






















{% comment %} {% extends "base.html" %}
{% block content %}
<div>
    <h1>My Projects</h1>
    {% if projects_list|length < 1%}
    <p>You are not assigned to any projects</p>
        {% elif projects_list %}
        <div>
            <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
            </thead>
            <tbody>
                {%for projects in projects_list%}
                <tr>
                <td>{{projects.name}}</td>
                <td>{{projects.|length}}</td>
                </tr>
                {% endfor %}  
            </tbody>
        </table>  
    </div>  
    {% endif %}
</div>
{% endblock content %} {% endcomment %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>My Tasks</h1>
        {% if task_list|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Is Completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tasks in task_list %}
                        <tr>
                            <td>{{tasks.name}}</td>
                            <td>{{tasks.start_date}}</td>
                            <td>{{tasks.due_date}}</td>
                            <td>
                                {%if tasks.is_completed == False %}
                                    <form method="post" action="{% url 'complete_task' tasks.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {% else %}
                                    Done
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
        {% else %}
            <p>You have no tasks</p>
            </table>
        {% endif %}
    </div>
{% endblock content %}